package:
  name: fastlinkcheck
  version: 0.0.7
source:
  sha256: 665906ce05ee729c3e1f5aec4f2e2f5fcb731cb46fdf8297d556312c9f5b15b9
  url: https://files.pythonhosted.org/packages/4a/19/9fda14124f38d1d8112e84f9fa1dfb1e632d3b04954bd4a3391e56fd3254/fastlinkcheck-0.0.7.tar.gz
about:
  dev_url: https://fastlinkcheck.fast.ai
  doc_url: https://fastlinkcheck.fast.ai
  home: https://fastlinkcheck.fast.ai
  license: Apache Software
  license_family: APACHE
  summary: A python library
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - fastai
requirements:
  host:
  - pip
  - python
  - packaging
  - fastcore
  run:
  - pip
  - python
  - packaging
  - fastcore
test:
  imports:
  - fastlinkcheck
