package:
  name: fastlinkcheck
  version: 0.0.3
source:
  sha256: 9d2534e6d24bb38f893c03bb843bd11e574974d079b67e2314557aff8697c9a0
  url: https://files.pythonhosted.org/packages/b1/fd/213d8df6aa9c5effeddfe84146f0c3e103c14e067a232b98ff8bcf8ae68b/fastlinkcheck-0.0.3.tar.gz
about:
  dev_url: https://fastlinkcheck.fast.ai
  doc_url: https://fastlinkcheck.fast.ai
  home: https://fastlinkcheck.fast.ai
  license: Apache Software
  license_family: APACHE
  summary: A python library
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - fastai
requirements:
  host:
  - pip
  - python
  - packaging
  - fastcore
  run:
  - pip
  - python
  - packaging
  - fastcore
test:
  imports:
  - fastlinkcheck
