
name: Check Links
on: 
  workflow_dispatch:
  push:

jobs:
  fastcore:
    runs-on: ubuntu-latest
    container: fastai/fastai 
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Check links
      run: |
        pip install linkcheck_action
        check_links_action
      env:
        INPUT_PATH: "_example"
        INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_RAISE_ERROR: "True"
        INPUT_ISSUE_TITLE: "[Automated] Broken Links Found"
